### ISSUE TITLE
Avaliação de integração stripe

### ISSUE THREAD

**Issue by filiperochalopes** [Social-Pipe/social-docker#1]
Avaliar quais os dados necessários para realização de checkout transparente para pagamentos recorrentes

**Comment by filiperochalopes** [comment]
No momento preciso apenas do email @guilessa

**Comment by guilessa** [comment]
Filipão, segue o email, conforme combinado só que pela Pagar.me.

passari.socialpipe@gmail.com

**Comment by filiperochalopes** [comment]
- [ ] Criar hash de cartão https://docs.pagar.me/docs/obtendo-os-dados-do-cartao
- [ ] Criar plano https://docs.pagar.me/docs/planos
- [ ] Criar assinatura  https://docs.pagar.me/docs/assinaturas

**Comment by guilessa** [comment]
1. Plano Mensal
2. R$ 6,90 por cliente na plataforma (No exemplo da tela tem a Coca Cola, caso queira adicionar mais R$ 6,90)
3. 1 mês
4. Se possível 7 dias 

Quanto ao formulário, vou adicionar hoje.

**Comment by filiperochalopes** [comment]
Eu tinha entendido que o pagamento era por usuário e não por cliente. Ou seja, aquela tela lá fora no cadastro de pagamento não é funcional, pq na verdade o pagamento deve ser pedido toda vez que eu quiser colocar um novo cliente em meu dashboard. Logo a estrutura tem que ser diferente.
