### ISSUE TITLE
[ Cadastro ] Retirar placeholders dos seguintes inputs

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#10]
- NOME
- EMAIL
- CELULAR

**Comment by lucasnetwork** [comment]
![Captura de Tela (412)](https://user-images.githubusercontent.com/47489963/125101216-5d5a5880-e0b0-11eb-9691-4a3deadb07b6.png)
Removidos os placeholders pedidos

**Comment by guilessa** [comment]
Perfeito!
