### ISSUE TITLE
[ Cadastro ] Adicionar obrigatoriedade e verificação no preenchimento em todos os campos de cadastro

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#12]
Um exemplo é que se não preenchermos o campo EMAIL o cadastro continua sem problemas.

**Comment by lucasnetwork** [comment]
Consertado o erro

**Comment by guilessa** [comment]
@lucasnetwork perfeito mano. Só poderíamos colocar alguma forma de avisar onde precisa ser preenchido, o mais básico possível, podendo até mesmo usar aquela própria notificação do HTML. Ou talvez deixar o campo vermelho e aparecer embaixo "campo obrigatório", só para deixarmos melhor a UX.

**Comment by lucasnetwork** [comment]
Ok, vou adicionar

**Comment by lucasnetwork** [comment]
> @lucasnetwork perfeito mano. Só poderíamos colocar alguma forma de avisar onde precisa ser preenchido, o mais básico possível, podendo até mesmo usar aquela própria notificação do HTML. Ou talvez deixar o campo vermelho e aparecer embaixo "campo obrigatório", só para deixarmos melhor a UX. 

Ok, vou adicionar

**Comment by lucasnetwork** [comment]
https://user-images.githubusercontent.com/47489963/125501435-07a8e88f-e659-4207-9f4e-d8352f948343.mp4

Adicionado

**Comment by filiperochalopes** [comment]
Realizado deploy da versão atualizada.

**Comment by guilessa** [comment]
Perfeito!
