### ISSUE TITLE
[ Cadastro - Sucesso ] Alterar subtexto de SOCIALPIPE para Post Baker

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#13]

**Comment by lucasnetwork** [comment]
![Captura de Tela (407)](https://user-images.githubusercontent.com/47489963/125101434-95619b80-e0b0-11eb-9dd9-9406b0079d8e.png)
Alterado o texto

**Comment by guilessa** [comment]
Perfeito!
