### ISSUE TITLE
[ PagarMe ] Dúvida quanto a cancelamento de assinatura

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#15]
Pós cadastro recebemos um email da pagarme com a opção de GERENCIAR ASSINATURA.

Dentro dessa página temos, alterar cartão de crédito e cancelar assinatura. 

Temos como cancelar essas opções?

**Comment by filiperochalopes** [comment]
> Dentro da dashboard, indo em: Ver minha conta > Recorrência, tem um tópico de "enviar e-mail para os clientes", pode ser marcado como não. Daí esses e-mails param. Porém, marcando "não" ele não receberá mais nenhum e-mail sobre recorrência.
> Você também pode alterar o Layout dos seus e-mails, indo em: Ver minha conta > E-mails. Lá consegue configurar o layout e deixar apenas os botões que precisar no e-mail. Esse artigo pode lhe ajudar: https://docs.pagar.me/docs/conceitos-de-recorr%C3%AAncia
> E aqui, como personalizar os e-mails:
> https://pagarme.zendesk.com/hc/pt-br/articles/204766409-Como-personalizar-os-e-mails-de-recorr%C3%AAncia

Resposta de Luiz da Pagar.me

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/125290341-9421b000-e2f6-11eb-8415-0750e083c072.png)

**Comment by guilessa** [comment]
@filiperochalopes não entendi. Não tem problema de ter a opção de cancelar a assinatura pela Pagar.me. Meu problema é se vai ter um feedback ao sistema. Até porque pelo Pagar.me acredito que seja a única forma que tenho por exemplo de cuidar das questões financeiras e de usuários.

**Comment by filiperochalopes** [comment]
Sim, a gerência das questões financeiras serão realizadas pelo próprio dashboard da Pagarme. Já o gerenciamento do usuário, aparentemente não foi pensado nisso no projeto, mas por está desenvolvido em Django temos um painel administrativo que você pode ter acesso e editar tudo! Dá uma olhada:  
[http://162.214.108.8:88/admin](http://162.214.108.8:88/admin)  
email root de teste: contato@filipelopes.me  
senha: passw@rd  

Um plus de nosso serviço. :smile: 
Está com dados bem simplificados, mas pode ser expandido, se solicitado. Pode ser de grande valia. Porém nessa versão você já pode ver a opção de desativar usuário, que creio que é o que vc gostaria.

**Comment by guilessa** [comment]
Ahhhh top! Perfeito! Hahah
