### ISSUE TITLE
[ PagarMe ] Cancelamento direto pela PagarMe

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#16]
Fiz um teste e quando cancelamos a assinatura direto pela PagarMe não altera a assinatura na plataforma, precisar de uma forma que isso seja conversável ou se for possível deixar essa opção ativa, apenas pela nossa plataforma.

**Comment by filiperochalopes** [comment]
Com a resolução da issue https://github.com/Social-Pipe/social-docker/issues/15 creio que não teremos mais problemas com isso. Aguardo retorno.

**Comment by guilessa** [comment]
Filipe, será que vai ser ajustar mesmo? Estou com esse receio desse feedback do Pagarme com o sistema. Da galera conseguir cancelar por lá e continuar ativo aqui. 

Digo isso porque minha conta guilesssa@gmail.com ainda está ativa e eu fiz o cancelamento por lá.

**Comment by filiperochalopes** [comment]
Sim, isso pq você recebeu o email para cancelar a assinatura, mas não mais receberão esse email, como eu falei na outra issue. Os emails foram cancelados.

**Comment by guilessa** [comment]
Ahhh perfeito! Então fechado!
