### ISSUE TITLE
[ Pagarme ] Dúvida final sobre pagamento

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#17]
Minha dúvida é sobre o seguinte exemplo.

Ex: Quando um usuário está no meio dos 7 dias, caso ele adicione mais 3 clientes, a fatura vai vir com R$ 6,90 x 4 certo?

**Comment by filiperochalopes** [comment]
O primeiro cliente ele tem direito aos 7 dias. O segundo é debitado na hora os 6,90 e então depois de um mês ele receberá 4 cobranças de R$6,90. Exatamente.

**Comment by guilessa** [comment]
Perfeito! Entendido. Estou fazendo essas perguntas só parar ter certeza em caso de atendimento ou FAQ.
