### ISSUE TITLE
[ Layout ] Ajustar footer na pagina de usuário 

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#18]
![InShot_20210715_181040302](https://user-images.githubusercontent.com/25805990/125858251-facafeaf-2833-4b96-a350-b3cb96a0dff7.jpg)

**Comment by filiperochalopes** [comment]
Não compreendi essa issue, compreendeu @lucasnetwork ?

**Comment by lucasnetwork** [comment]
@filiperochalopes não, não entendi a questão.

**Comment by guilessa** [comment]
Perdão, foto errada. Segue a foto certa.

O "Aprovando postagens" está bem agarrado lá embaixo. Não segue o padrão da home do dashboard. 

Agora foi! 

![Captura de Tela 2021-07-15 às 22 34 25](https://user-images.githubusercontent.com/25805990/125878356-7f8efdad-0018-4dff-9b9c-0a6a9c6155e3.png)

**Comment by lucasnetwork** [comment]
![Captura de Tela (438)](https://user-images.githubusercontent.com/47489963/125958103-f5e269ed-8b6e-4941-b2e1-f0b4a9c1a200.png)
Consertado

**Comment by guilessa** [comment]
Perfeito!
