### ISSUE TITLE
[ Layout ] Botao de copiar link

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#19]
Quando clicamos no botão copiar o link de acesso do painel do cliente, ele copia apenas o código. É possível, copiar o link completo?

**Comment by filiperochalopes** [comment]
Com certeza, @lucasnetwork. Você pode pegar o host com js, seria algo como:  
```js
const getUrl = window.location;
const baseUrl = `${getUrl .protocol}//${getUrl.host}/cliente/${hash}`
```

**Comment by lucasnetwork** [comment]
@filiperochalopes blz, vou adicionar isso.

**Comment by lucasnetwork** [comment]
Adicionado

**Comment by guilessa** [comment]
Shoow!
