### ISSUE TITLE
[ Erros ] Erro ao apagar post e cliente 

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#20]
Aparece um erro de conexão ao apagar post e não é possível apagar cliente.

**Comment by guilessa** [comment]
![InShot_20210715_181128536](https://user-images.githubusercontent.com/25805990/125858698-bfaeea5c-a332-44d7-9b0c-7167040d6938.jpg)

**Comment by filiperochalopes** [comment]
@lucasnetwork verificar que tipo de erro a requisição retorna, se do tipo 400 ou 500

**Comment by lucasnetwork** [comment]
https://user-images.githubusercontent.com/47489963/125873291-6827b2e5-769a-454b-941c-719fe6afa119.mp4

Consertado

**Comment by guilessa** [comment]
Perfeito!

**Comment by guilessa** [comment]
Erro quando tento adicionar novo cliente

![Captura de Tela 2021-07-30 às 16 03 39](https://user-images.githubusercontent.com/25805990/127700422-e00f4408-deb4-423c-9631-e7142c9525b7.png)

Erro quanto tento apagar cliente

![Captura de Tela 2021-07-30 às 16 06 57](https://user-images.githubusercontent.com/25805990/127700499-bda6361d-36c4-42b4-9ca1-e590d44d40a4.png)

**Comment by filiperochalopes** [comment]
Erro ao apagar cliente persiste, isso antiga @lucasnetwork

**Comment by filiperochalopes** [comment]
Concluído, segundo @lucasnetwork . Favor proceder com a verificação.

**Comment by guilessa** [comment]
Fala time, o erro por aqui permanece.

**Comment by lucasnetwork** [comment]
@guilessa o erro permanece igual, sem os detalhes do erro?

**Comment by guilessa** [comment]
Fala @lucasnetwork, assim que clico em **apagar agora** gera esse erro.

![Captura de Tela 2021-08-04 às 18 28 55](https://user-images.githubusercontent.com/25805990/128257372-9860b814-40ca-4312-9d50-002b17b5fbd8.png)

**Comment by filiperochalopes** [comment]
@guilessa O site tinha subido com algumas atualizações e outras não, por conta de configurações do git, agora aparentemente está tudo ok. peço desculpas e que tente novamente.

**Comment by filiperochalopes** [comment]
Já tem 5 dias que não tem retorno, foi verificada a correção? @guilessa

**Comment by guilessa** [comment]
Fala pessoal, perfeito! Estava sem usuário por isso não consegui testar. Mas está funcionando PERFEITAMENTE!
