### ISSUE TITLE
[ Painel Usuário ] Erro ao alterar senha e estado não aparece

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#21]
Quando tento alterar senha, não funciona. Se estiver funcionando, não estou recebendo nenhum feedback avisando que deu certo. 

E o estado nas infos do usuário não aparece o selecionado pelo user.

**Comment by filiperochalopes** [comment]
Não compreendi essa frase "E o estado nas infos do usuário não aparece o selecionado pelo user.", poderia ser mais claro? Teria algum prinscreen?

**Comment by guilessa** [comment]
![Captura de Tela 2021-07-16 às 13 38 03](https://user-images.githubusercontent.com/25805990/125980632-47d62850-d00c-4ba7-b3c5-047c90f63c67.png)

**Comment by lucasnetwork** [comment]
https://user-images.githubusercontent.com/47489963/125986418-a5eba90a-d61f-4086-917a-e7acd7d86ef0.mp4

Consertado

**Comment by guilessa** [comment]
Perfeito!
