### ISSUE TITLE
[ Layout ] Botão para visualizar senha de acesso do cliente

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#22]
Pessoal, é possível colocar um botão para visualizar a senha, ou até mesmo deixar a senha aberta? 

**Opinião:** Não vejo necessidade de manter a senha com os **** tendo em vista que se tornaria redundante colocar o botão de preview da senha. 

![Captura de Tela 2021-07-15 às 22 37 49](https://user-images.githubusercontent.com/25805990/125878683-bc4c5756-8739-435c-816b-c92e6f9e9dbc.png)

**Comment by filiperochalopes** [comment]
Deixar a senha aberta é uma opção, porém, a partir do momento que ela é salva há uma criptografia, conforme solicitado. Nunca mais ninguém consegue saber qual é essa senha. Então depois de salva não é possível mais visualizá-la por motivos de segurança, não teria, dessa forma, como mostrar. Mas se é só na parte de criação de senha, é possível sim deixar aberta, entraria como uma funcionalidade a ser orçada, pois não estava no acordo.

**Comment by guilessa** [comment]
Entendi, então mantemos assim. Não posso ter custos adicionais por enquanto.
