### ISSUE TITLE
[ Editar Post ] Quando tentamos alterar a imagem ela apaga

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#24]
Quando vamos em "editar post" e escolhemos uma nova imagem, ela some assim que salvamos. 

![Captura de Tela 2021-07-15 às 22 49 43](https://user-images.githubusercontent.com/25805990/125879426-f711e8ae-43d0-4c87-8e25-3129ccb2f6b2.png)

**Comment by lucasnetwork** [comment]
@guilessa No caso, se ele escolher uma outra imagem, é para ela ser adicionada junto a outra imagem?, por agora, isso é feito manualmente quando o usuário seleciona carrousel.

**Comment by guilessa** [comment]
Não. Na verdade o erro acontece quando tentamos selecionar uma nova imagem ao editar um post.

Perdão, parece que não está acontecendo mais, ou poderia ser alguma imagem que escolhi.

**Comment by lucasnetwork** [comment]
Entendi, vou ver então se consigo reproduzir o erro pra corrigir isso.

**Comment by filiperochalopes** [comment]
@guilessa Teria como adicionar um vídeo? gravando o procedimento para facilitar? É muito prático utilizando o [Loom](https://www.loom.com/)

**Comment by guilessa** [comment]
Fala time, segue o vídeo. 


https://user-images.githubusercontent.com/25805990/126264118-fe3f92e2-f73a-4cbe-aaf4-16acec99ca06.mov

**Comment by filiperochalopes** [comment]
Ao editar post e salvar sem fazer alteração nenhuma, a imagem do post é retirada! @lucasnetwork Vide vídeo acima. Creio que é um problema na hora de carregar o formulário de edição com as informações e acaba enviando informações de imagem em branco na hora de fazer o `PATCH`. Precisa dar uma olhada.

**Comment by lucasnetwork** [comment]
https://user-images.githubusercontent.com/47489963/126344857-31ea371b-8c26-426b-83b0-e8656f018369.mp4

Corrigido

**Comment by guilessa** [comment]
Perfeito!
