### ISSUE TITLE
[ Preview - Post ] Botão de passar para o lado

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#25]
É possível adicionar os botões de anterior e próximos nos posts tipos carrossel? Tipo do Instagram mesmo.

**Comment by guilessa** [comment]
![Captura de Tela 2021-07-15 às 22 51 53](https://user-images.githubusercontent.com/25805990/125879621-1cfc7fd2-adca-429a-8592-7b02ca5839d5.png)

**Comment by filiperochalopes** [comment]
Como estava prevista essa funcionalidade de visualização de carrousel @guilessa ? Não lembro.

**Comment by guilessa** [comment]
![Captura de Tela 2021-07-16 às 13 28 53](https://user-images.githubusercontent.com/25805990/125979654-ec37dded-903f-4bf0-be87-749c4718fe48.png)

**Comment by lucasnetwork** [comment]
![Captura de Tela (457)](https://user-images.githubusercontent.com/47489963/126040261-923f6a93-754d-40eb-9e0e-07a3d937bb4c.png)
Adicionado

**Comment by guilessa** [comment]
Perfeito!
