### ISSUE TITLE
[ Previews Posts ] Tamanho das imagens

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#26]
Pessoal, acredito que essa aqui seja a última ISSUE, graças a Deus! 

Adicionei na imagem a explicação de como gostaria que fosse por padrão. Essa ISSUE também é conectada a #25 sobre adicionar os botões no carrossel para melhorar a passagem das imagens. 

Qualquer dúvida estou a disposição. 
![Padrao](https://user-images.githubusercontent.com/25805990/125880754-ccad1aa7-649b-4765-9b4f-1b7d5c12df6e.jpg)

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/125965078-debd2859-24a1-47e3-a7ae-673089b5906c.png)  
Não compreendi essa frase. Em resumo, você quer que o *aspect ratio* da tela de visualização seja sempre 1:1? É isso?

**Comment by guilessa** [comment]
Exato!

**Comment by lucasnetwork** [comment]
![Captura de Tela (455)](https://user-images.githubusercontent.com/47489963/126002874-4c10631e-87f7-4f14-9866-1fbba00f9293.png)


Agora o container das imagens está com o tamanho 1:1, exceto quando ele estiver em formato mobile, que a altura vai ser menor que a largura. 

![localhost_3000_dashboard_cliente_6_post (1)](https://user-images.githubusercontent.com/47489963/126002985-773efae5-2acd-4d08-b0b9-1c7b80a7d21c.png)

**Comment by guilessa** [comment]
Perfeito!

**Comment by guilessa** [comment]
Fala pessoal, esse erro voltou.

**Comment by filiperochalopes** [comment]
@guilessa na verdade você tinha olhado apenas o printscreen e não tinha chegado a testar. Peço que não feche as issues por conta dos printscreens na tela pois as vezes em nosso computador pode ter um comportamento diferente do servidor, de qualquer forma...  

@guilessa O site tinha subido com algumas atualizações e outras não, por conta de configurações do git, agora aparentemente está tudo ok. peço desculpas e que tente novamente.

**Comment by filiperochalopes** [comment]
Já tem 5 dias que não tem retorno, foi verificada a correção? @guilessa

**Comment by guilessa** [comment]
Acabei de testar! Não estava conseguindo devido usuário. **PERFEITO!!!**
