### ISSUE TITLE
[ Chatbot ] Se possível adicionar código JIVOCHAT

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#27]
É possível adicionar esse código do JIVOCHAT para suporte dos clientes? 

<script src="//code-sa1.jivosite.com/widget/WW2aHNpmUz" async></script>

Essa é boa? Uma dúvida!

**Comment by filiperochalopes** [comment]
Não conheço os serviços da JivoChat, mas sim, posso adicionar essa linha de código ao seu site. @lucasnetwork , favor colocar no final do body, fora da div #root , no arquivo `index.html` dentro de `/public`.

**Comment by lucasnetwork** [comment]
![Captura de Tela (447)](https://user-images.githubusercontent.com/47489963/125975721-1ffcee96-f450-4104-8aa3-202c39271508.png)
Adicionado

**Comment by guilessa** [comment]
Top!
