### ISSUE TITLE
[ Upload Vídeo ] Não estou conseguindo adicionar vídeo e progresso de upload

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#29]
Fala time. 

Na parte de upload de vídeo tem dois bugs e uma correção.

1. Quando escolho o vídeo a caixa fica estranha, diferente de quando escolhemos uma imagem. 
2. Escolhi o vídeo e não consigo salvar o post. Talvez por ele não ter subido completamente, mas não vejo uma barra de upload para saber quando posso apertar salvar. 
3. A barra de upload, seria interessante só para termos um feedback.

**Comment by lucasnetwork** [comment]
@guilessa No caso, os arquivos são subidos quando o post é criado, então o frontend deve está com algum erro de identificar o vídeo e subir ele.

**Comment by filiperochalopes** [comment]
Não é tão simples fazer uma barra de upload e não estava previsto, no máximo poderíamos colocar um *spinning loading*, @guilessa , poderia colocar um vídeo mostrando, por texto as vezes é difícil visualizar com [Loom](https://www.loom.com/) é bem simples gravar

**Comment by lucasnetwork** [comment]
![Captura de Tela (474)](https://user-images.githubusercontent.com/47489963/126199017-71af3e0f-ac2a-4a5a-9eea-fec81148eb7e.png)
Sobre a questão 1 e 2, esses dois problemas foram resolvidos

**Comment by guilessa** [comment]
@filiperochalopes por mim perfeito o spin loading. Só precisaria mesmo de algo para mostrar aos usuários que tem algo acontecendo. 

@lucasnetwork perfeito mano! Mais uma vocês arrebentando!

**Comment by guilessa** [comment]
Um exemplo talvez, aqui do próprio Github. 

![Captura de Tela 2021-07-20 às 01 56 54](https://user-images.githubusercontent.com/25805990/126264191-a42aaba6-81d1-448a-a5b1-65357cd5370f.png)

**Comment by filiperochalopes** [comment]
Pronto então @lucasnetwork , colocar um spin loading embaixo do input mesmo,  
![image](https://user-images.githubusercontent.com/34348097/126311284-537ebe02-4da4-43f7-a86d-052902c1aaec.png)  
Só para informar que está carregando. Pode ser um gif giratório.  
![loading](https://user-images.githubusercontent.com/34348097/126312140-4927331c-fc14-4a2e-91d1-34d5e27cd673.gif)  
https://tenor.com/view/loading-buffering-spinning-waiting-gif-17313179 (pode salvar ela daqui clicando com o botão direito e deixar bem pequeno embaixo do campo quando tiver carregando algo.

**Comment by guilessa** [comment]
Perfeito!

**Comment by lucasnetwork** [comment]
Bom dia gente, terminando essa questão, adicionei o spin de loading igual  o do botão mesmo, vai aparecer enquanto os arquivos são mandados para o backend.

![Captura de Tela (487)](https://user-images.githubusercontent.com/47489963/126513506-ac732d3d-8472-4105-851b-59595f5bddf7.png)
![Captura de Tela (489)](https://user-images.githubusercontent.com/47489963/126514457-d7157e3c-77af-40ad-8c75-e84507b46f1e.png)

Adicionei tambem um botão de retry caso ocorrer um erro durante o upload de arquivos.

![Captura de Tela (486)](https://user-images.githubusercontent.com/47489963/126513704-aac5b3b0-7f84-456e-a7ad-9dbbb08e4bed.png)
![Captura de Tela (488)](https://user-images.githubusercontent.com/47489963/126514587-908ee071-781a-4def-984b-4b6aecb8afea.png)

**Comment by guilessa** [comment]
Caramba, ficou top demais! Perfeito!
