### ISSUE TITLE
[ Layout ] Alteração no preço na opção de novo cliente 

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#30]
Fala time, 

É possível alterar para o preço padrão R$ 6,90? 

![Captura de Tela 2021-07-30 às 16 05 01](https://user-images.githubusercontent.com/25805990/127700325-3ade8019-5689-4b33-85ac-7bfbe14cbde5.png)

**Comment by filiperochalopes** [comment]
Sim, farei isso.

**Comment by filiperochalopes** [comment]
Alterado.

**Comment by guilessa** [comment]
Perfeito!
