### ISSUE TITLE
[ Erro ] Ao tentar acessar o link de visualização no modo cliente

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#31]
Quando acesso o link aparece esse erro. 

![Captura de Tela 2021-07-30 às 16 07 40](https://user-images.githubusercontent.com/25805990/127700608-89a84a3c-3a8d-4eca-8ce7-682a22d9cd9c.png)

**Comment by filiperochalopes** [comment]
Qual link? Precisamos de uma explicação melhor do erro. Teria como mandar um loom ou vídeo?

**Comment by guilessa** [comment]
@filiperochalopes o link de acesso do cliente, de todos os projetos que eu crio. 

https://app.postbaker.com.br/OYKthCThqn0Bqo7F

**Comment by filiperochalopes** [comment]
Infelizmente não compreendo por completo o problema, quando vc copia o código e coloca no browser, ao abrí-lo você tem a página demonstrada na descrição da issue? É isso? As informações estão soltas. Favor confirmar ou explicar melhor como o bug ocorre.

**Comment by guilessa** [comment]
O erro permance. Segue o vídeo explicando o mesmo.


https://user-images.githubusercontent.com/25805990/128256420-edc2e217-7153-4302-aa12-33689cc63427.mov

**Comment by filiperochalopes** [comment]
Entendi, @lucasnetwork. Favor corrigir.

**Comment by filiperochalopes** [comment]
@guilessa O site tinha subido com algumas atualizações e outras não, por conta de configurações do git, agora aparentemente está tudo ok. peço desculpas e que tente novamente.

**Comment by filiperochalopes** [comment]
Já tem 5 dias que não tem retorno, foi verificada a correção? @guilessa

**Comment by guilessa** [comment]
Perfeito! Não estava conseguindo testar porque estava sem o usuário aqui.
