### ISSUE TITLE
[ Layout ] Tela do post muito grande

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#32]
Na imagem abaixo mostra o popup de edição de post e visualização bem grane, colado no topo e na parte inferior do navegador. 

![Captura de Tela 2021-07-30 às 16 10 41](https://user-images.githubusercontent.com/25805990/127700980-a4f5aa01-c21e-4c7b-ba2a-e551670cb256.png)

Segue como está no XD.

![Captura de Tela 2021-07-30 às 16 10 32](https://user-images.githubusercontent.com/25805990/127701007-986de07a-da1d-4171-bc06-019b6ee233de.png)

**Comment by filiperochalopes** [comment]
O período de garantia expirou em 22/07 e como esse erro não foi reportado até o prazo de garantia, será adicionado como melhoria a ser desenvolvida a partir do dia 01/08.

**Comment by guilessa** [comment]
Como um "erro" é adicionado como "melhoria" enfim, ok, no aguardo.

**Comment by filiperochalopes** [comment]
Nos desenvolvimentos da empresa classificamos como **Bug**
- Recursos que não consigam ser acessados por erro de código e que estavam listados como funcionalidade
- Ajustes de layout que foram identificados para mudança dentro do prazo de garantia  
As demais atividades são tratadas como melhorias.  
Essa atividade será desenvolvida assim que possível dentro do mês atual.

**Comment by filiperochalopes** [comment]
Corrigida por @lucasnetwork

**Comment by guilessa** [comment]
Fala time, eu acabei precisando reabrir uma  ISSUE (#26) devido ao retorno do erro referente a escala das imagens.

Em anexo uma imagem que fiz o upload em 1080x1920 (tamanho de story) e voltou a ficar sem aquela mudança que havia sido feita nessa ISSUE reaberta (#26).

![Captura de Tela 2021-08-04 às 18 15 41](https://user-images.githubusercontent.com/25805990/128255942-af71ea8b-7cf0-43f9-b8ad-9a5a3778c2c8.png)

**Comment by filiperochalopes** [comment]
@guilessa O site tinha subido com algumas atualizações e outras não, por conta de configurações do git, agora aparentemente está tudo ok. peço desculpas e que tente novamente.

**Comment by lucasnetwork** [comment]
@guilessa o aspecto que pediu para o container da imagem é em 1:1 ou 9:16?

**Comment by filiperochalopes** [comment]
> @guilessa o aspecto que pediu para o container da imagem é em 1:1 ou 9:16?

Não compreendi a perguta.

**Comment by lucasnetwork** [comment]
> > @guilessa o aspecto que pediu para o container da imagem é em 1:1 ou 9:16?
> 
> Não compreendi a perguta.

![app postbaker com br_dashboard_cliente_6_post](https://user-images.githubusercontent.com/47489963/128718889-d85efb31-4143-4912-b3c3-c9d9e2c8ebbf.png)

testei aqui com uma imagem 1080X1920, o container ficou normal em 1:1, aí minha duvida se é 1:1 ou 9:16, a menos que seja em outro formato de tela que não testei.

**Comment by guilessa** [comment]
Fala @lucasnetwork ficou perfeito mano!

1:1 é o padrão que o próprio Instagram usa. Estou pensando em estar sempre parecido com os caras tendo em vista que os usuários já estão habituados com a UI.

**Comment by guilessa** [comment]
PERFEITO!
