### ISSUE TITLE
[ Favicon + Title ] Alteração

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#33]
Title: Post Baker - Aprovação de Posts

Favicon em anexo:

[FaviconPostBaker.zip](https://github.com/Social-Pipe/social-docker/files/6909653/FaviconPostBaker.zip)

**Comment by filiperochalopes** [comment]
O período de garantia expirou em 22/07 e como esse erro não foi reportado até o prazo de garantia, nem tínhamos recursos teus para fazer esse ajuste, será adicionado como melhoria a ser desenvolvida a partir do dia 01/08.

**Comment by guilessa** [comment]
Filipe, sinceramente não faz sentido nenhum isso tendo em vista que o título seria o básico para qualquer aplicação, está como Reactapp, ainda parece que estamos em desenvolvimento.

Mas não tem problema, estou preocupado se com essa questão disso ser “melhoria” serei cobrado algum valor adicional.

**Comment by filiperochalopes** [comment]
Como observado no contrato, melhorias que sejam de pequeno impacto e julgado essenciais, pelo CONTRATADO, para melhorar experiencia de usuário estão inclusos no pacote. Quando for cobrado adicional não se preocupe que deixarei informado por aqui.

**Comment by filiperochalopes** [comment]
Atividade realizada, pode ser testada em app.postbaker.com.br  
![image](https://user-images.githubusercontent.com/34348097/127942302-fe3b3f1d-ec90-456d-bf9e-b527f5bd7b3d.png)

**Comment by guilessa** [comment]
Perfeito!
