### ISSUE TITLE
Erro ao cadastrar novo usuário

### ISSUE THREAD

**Issue by filiperochalopes** [Social-Pipe/social-docker#34]
Conforme relatado por @guilessa existe um erro ao tentar se cadastrar no sistema com novo usuário e as mensagens de erro não são tão específicas para poder avaliar o erro.

https://user-images.githubusercontent.com/34348097/127943262-f67c6470-774b-4c78-bc83-19ff0a280d5e.mp4

**Comment by guilessa** [comment]
Isso já foi resolvido, não?

**Comment by filiperochalopes** [comment]
Concluído, segundo @lucasnetwork

**Comment by guilessa** [comment]
Fala time, o erro permanece, dessa vez um pouco diferente. 

_1. Quando clico em finalizar uma cobrança é feita de R$ 0 no cartão, mas o usuário não é redirecionado para a página a próxima página, e aparece o erro do primeiro anexo;

2. Mesmo com esse erro, o cadastro é sim concluido, mas, o cliente principal não é adicionado automaticamente;_

**ERRO QUE APARECE AO APERTAR FINALIZAR**
![Captura de Tela 2021-08-04 às 18 22 46](https://user-images.githubusercontent.com/25805990/128256886-767c9aea-1ab7-4f71-9560-bd254f27a57b.png)

**MESMO COM ERRO O CADASTRO É FEITO, MAS O CLIENTE PRIMÁRIO NÃO É ADICIONADO AUTOMATICAMENTE**
![Captura de Tela 2021-08-04 às 18 23 23](https://user-images.githubusercontent.com/25805990/128257064-ffa52905-2b23-44b1-b911-23b36af72c8a.png)

**Comment by lucasnetwork** [comment]
@filiperochalopes acho que deve ser algo relacionado ao pagarme, porque em desenvolvimento, todos os passos do cadastro passam normalmente.

**Comment by filiperochalopes** [comment]
@guilessa O site tinha subido com algumas atualizações e outras não, por conta de configurações do git, agora aparentemente está tudo ok. peço desculpas e que tente novamente.

**Comment by guilessa** [comment]
Fala time, boa tarde.

Segue o erro que está acontecendo no registro de novo usuário. 

https://user-images.githubusercontent.com/25805990/128551391-cf2bef9d-342f-4a21-9e98-15911e08deef.mp4

**Comment by guilessa** [comment]
Fala time, o erro continua.

**Comment by filiperochalopes** [comment]
@guilessa Confirmo que o erro foi solucionado em produção. Utilizei o meu próprio cartão de crédito.  
https://www.loom.com/share/a4cd41b267f14135bcc907d91cf0c641  
Por favor verifique se não foi o cache do navegador. Atualize sempre a página com `Ctrl + F5` entre as atualizações do site.

**Comment by guilessa** [comment]
Perfeito! Fiz o teste aqui também e funcionou muito bem!
