### ISSUE TITLE
Erro na recuperação de senha

### ISSUE THREAD

**Issue by filiperochalopes** [Social-Pipe/social-docker#35]
Devido à mudança de domínio a recuperação de email está com erro nos servidores SMTP, relatado por @guilessa dessa maneira:  

https://user-images.githubusercontent.com/34348097/127943369-50a09c4b-65ea-4594-b6d8-332d971447d3.mp4

**Comment by filiperochalopes** [comment]
Corrigido.

**Comment by guilessa** [comment]
Isso já foi resolvido.

**Comment by guilessa** [comment]
Perfeito!
