### ISSUE TITLE
[ Bug ] Ao tentar criar novo cliente sem imagem de capa

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#38]
Fala time.

Quando tentamos criar um NOVO CLIENTE e não adicionamos a foto, aparece o erro de cartão de crédito. 

Talvez se colocarmos aquela mesma obrigação de inputs que tem no momento do cadastro já possa ser uma solução. 

Mas, se preenchermos com a imagem do cliente, tudo ocorre normalmente. 

https://user-images.githubusercontent.com/25805990/128758159-40d9169d-abea-42e1-89dd-9562ca8b4a86.mov

**Comment by lucasnetwork** [comment]
Corrigido, agora está igual ao de registro

**Comment by guilessa** [comment]
@lucasnetwork perfeito. É possível colocar aquela borda vermelha como na página de registro?

**Comment by lucasnetwork** [comment]
> @lucasnetwork perfeito. É possível colocar aquela borda vermelha como na página de registro?

Sim, da pra colocar isso

**Comment by filiperochalopes** [comment]
@guilessa Já foi desenvolvido. Sigo no aguardo de um retorno.

**Comment by guilessa** [comment]
Perfeito!
