### ISSUE TITLE
[ Erro ] Alterar imagens ou vídeo de um post já criado

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#39]
Parece que ele até salva mas o erro fica na tela. 

https://user-images.githubusercontent.com/25805990/128758941-a24b4181-11fd-4928-9db0-a81735d157c6.mov

**Comment by filiperochalopes** [comment]
Aí vc só clicou no botão @guilessa , vc alterou a imagem, pelo que eu entendi, aí na hora de salvar com a imagem trocada, deu esse erro.

**Comment by guilessa** [comment]
@filiperochalopes não entendi.

**Comment by filiperochalopes** [comment]
> @filiperochalopes não entendi.

Simplemente não tinha compreendido o bug, No vídeo você não seleciona nenhuma imagem. Solicitei uma explicação. @lucasnetwork foi investigada essa issue? Você compreendeu do que se trata?

**Comment by lucasnetwork** [comment]
> > @filiperochalopes não entendi.
> 
> Simplemente não tinha compreendido o bug, No vídeo você não seleciona nenhuma imagem. Solicitei uma explicação. @lucasnetwork foi investigada essa issue? Você compreendeu do que se trata?

Isso era um bug de salvar imagens, já foi corrigido também

**Comment by filiperochalopes** [comment]
Tudo bem então. Se já foi corrigido marcarei como tal e aguardarei o fechamento da mesma.

**Comment by guilessa** [comment]
Perfeito!
