### ISSUE TITLE
[ Login ] Retirar botão página de cadastro

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#4]
O botão grande em vermelho. Era apenas para facilitar o acesso durante o preview.

**Comment by lucasnetwork** [comment]
![Captura de Tela (401)](https://user-images.githubusercontent.com/47489963/125098221-39e1de80-e0ad-11eb-8657-d1a1bc9683ee.png)

**Comment by guilessa** [comment]
Perfeito!
