### ISSUE TITLE
[ Bug ] Envio de vídeo com falha

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#40]
Fala time. 

Ao tentar enviar vídeo o upload não é feito, mas o post é criado, sem o vídeo lá dentro. 

Estava em dúvida sobre o tamanho do vídeo liberado. Normalmente esses vídeos são grandes, vão de 100mb até 500mb de tamanho. Com certeza vão ter clientes tentando subir até mesmo vídeos maiores. 

Segue em anexo o erro. 

https://user-images.githubusercontent.com/25805990/128759974-e7518880-9324-4c63-a376-40c8f11406c7.mov

**Comment by filiperochalopes** [comment]
É, essa questão não tinha sido comentada. Sobre o tamanho dos vídeos. Certamente vídeos de instagram não são desse tamanho e podem ser compactados, também não foi solicitado limite para tamanho dos vídeos. Sendo assim nenhum dos dois foram feitos. Colocaremos apenas vídeos compactados de até 20mb, pois o espaço de disco não suportará arquivos maiores. @lucasnetwork, poderia dar uma olhada?  
- [ ] Verificar bug de envio
- [ ] Limitar tamanho de upload à 20mb e colocar aviso: "Tamanho máximo permitido de upload: 20mb, favor compactar o vídeo antes de realizar o upload"

**Comment by guilessa** [comment]
@filiperochalopes vídeos compactados de 20mb não é viável. Precisamos aumentar isso.

**Comment by filiperochalopes** [comment]
Conforme discutido, os arquivos se manterão com tamanho máximo de 20mb até que seja movida para outra hospedagem de maior capacidade. Fechando a issue.
