### ISSUE TITLE
[ Erro ] Senha do painel de visualização do cliente não altera

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#41]
Quando altero a senha de visualização ela não atualiza, se mantem na senha padrão de criação. 

Obs: Testei com navegadores diferentes, modo anonimo e usando wifi/4g. 

![Screenshot_20210813-191551_Chrome](https://user-images.githubusercontent.com/25805990/129423260-ecfb7525-a5a5-4e52-887f-b003cd4c5d8f.jpg)

**Comment by filiperochalopes** [comment]
@lucasnetwork . Campo de `password` adicionado ao PATCH. Proceder com verificação e correção.

**Comment by lucasnetwork** [comment]
@filiperochalopes mesma coisa, não está alterando a senha

formato que estou enviando:
{
"name":"lucas"
"instagram": false
"facebook": false
"linkedin": true
"linkedin": true
"password ": "12345678"
}

**Comment by filiperochalopes** [comment]
Pronto, consegui.
![image](https://user-images.githubusercontent.com/34348097/129453550-87f4b81b-d863-4b2c-8bbd-e3421bc03dc0.png)
Tive que reconstruir o endpoint. Tudo ok agora aparentemente.

**Comment by lucasnetwork** [comment]
testei aqui tambem, tudo certo

**Comment by guilessa** [comment]
Perfeito!
