### ISSUE TITLE
[ UX ] Botão de play quando o criativo for vídeo

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#42]
Time, boa noite. 

O vídeo está iniciando sozinho, mas logo após o termino da reprodução, não está sendo possível dar play novamente, ou controlar a reprodução do vídeo. 

Por hora se for possível colocar apenas o botão de play já basta como está no segundo print. 

![Screenshot_20210813-191806_Chrome](https://user-images.githubusercontent.com/25805990/129423417-e8abb8d6-1594-491f-930c-2830105d489e.jpg)

PRINT 02
![Screenshot_20210813-192004_Chrome](https://user-images.githubusercontent.com/25805990/129423556-927412e6-6563-4ae8-bbdb-75e4c6f15869.jpg)

**Comment by filiperochalopes** [comment]
Colocar esse play grande não foi a solução que encontramos, por se tratar de um bug que necessita de correção rápida, habilitamos os controllers de vídeo do HTML.

**Comment by guilessa** [comment]
Fala @filiperochalopes perfeito assim, muito top! 

Só gostaria de saber se é possível desativar o "autoplay", se sim, perfeito.

**Comment by guilessa** [comment]
Fala time, boa tarde!

Conseguimos desativar essa questão do autoplay?

**Comment by guilessa** [comment]
Conseguimos desativar essa questão do autoplay?

**Comment by guilessa** [comment]
Conseguimos desativar essa questão do autoplay?

**Comment by filiperochalopes** [comment]
Após 14 de Agosto demos por concluído quando atendemos a rua primeira solicitação. Não consegui ver essa requisição do autoplay senão hoje. Vou fazer essa mudança agora.

**Comment by filiperochalopes** [comment]
Feito, está em teste e subirei para produção em breve

**Comment by filiperochalopes** [comment]
Nova versão enviada para produção.
