### ISSUE TITLE
[ AGRADECIMENTO ]

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#43]
Quero agradecer de coração pelo trabalho. Esse é um sonho que está sendo realizado e só Deus sabe o quanto sonhei com isso, um pouco mais de 1 e meio para tomar coragem e investir nessa nova startup depois de muita porrada. 

Eu sou o tipo de cara bem testador, busco no detalhe e sempre tento buscar uma solução pra agilizar o projeto, espero que entendam. 

Mais uma vez agradeço de coração! Vamos pra cima!

**Comment by filiperochalopes** [comment]
> "Em todo trabalho há proveito; meras palavras, porém, levam à penúria (pobreza)." Pv 14:23  

> "Empregue o seu dinheiro em bons negócios e com o tempo você terá o seu lucro. Aplique-o em vários lugares e em negócios diferentes porque você não sabe que crise poderá acontecer no mundo. [...] Semeie de manhã e também de tarde porque você não sabe se todas as sementes crescerão bem, nem se uma crescerá melhor do que a outra." Ec 11:1,2,6  

Deus abençoe e faça crescer todos os caminhos segundo a vontade Dele!

**Comment by lucasnetwork** [comment]
> Quero agradecer de coração pelo trabalho. Esse é um sonho que está sendo realizado e só Deus sabe o quanto sonhei com isso, um pouco mais de 1 e meio para tomar coragem e investir nessa nova startup depois de muita porrada.
> 
> Eu sou o tipo de cara bem testador, busco no detalhe e sempre tento buscar uma solução pra agilizar o projeto, espero que entendam.
> 
> Mais uma vez agradeço de coração! Vamos pra cima!

Que dê tudo certo e cresça com o seu projeto

**Comment by filiperochalopes** [comment]
Issue sem novas contribuições.
