### ISSUE TITLE
[ Dúvida ] Posso abrir o sistema?

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#44]
Fala time, boa tarde.

Eu posso iniciar o sistema? Para outros usuários. 

Abs., tenham uma ótima semana!

**Comment by filiperochalopes** [comment]
Bom dia Guilherme. Desde sempre já pôde fazê-lo. :see_no_evil: O que não queríamos era subir com bugs, por isso às correções, mas já está liberado para abrir desde o momento que transferimos a chave do cartão para a real. Então sinta-se livre para isso.

**Comment by guilessa** [comment]
Tooop! Finalizando o resto da estrutura da empresa para começar o job!
