### ISSUE TITLE
[ Erros ] Ao cadastrar e ao tentar recuperar senha

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#47]
Quando tento fazer o cadastro e recuperar aparece a mensagem:

"Erro, tente novamente"

**Comment by filiperochalopes** [comment]
Favor realizar o teste na nova versão. Se você me passar suas credenciais de uso posso debugar melhor para você. Como eu disse previamente, as vezes é ruim debugar em produção por conta das taxas com cartão de crédito.
