### ISSUE TITLE
[ Erro ao se cadastrar ] Mais uma vez

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#50]
Já reclamei disso, algumas vezes, mas o erro o problema continua. 

O usuário ainda consegue se cadastrar sem inserir os dados do cartão de crédito. Ao clicar finalizar cadastro com campos em branco ainda é possível se cadastrar. 

Por favor, adicionar campos obrigatórios no formulário, como padrão em qualquer sistema de login e cadastro, POR FAVOR!

**Comment by filiperochalopes** [comment]
NÃO CONSEGUI REPRODUZIR ESSE ERRO!!  
![image](https://user-images.githubusercontent.com/34348097/153414142-7c5e4e90-2ee5-4162-98b4-65d3fb51f316.png)
Ao tentar cadastrar o usuário sem dados de cartão de crédito ele informa que é necessário os dados do cartão de crédito dizendo "Campo Obrigatório" conforme a imagem. É importante lembrar que o seu computador, por ter testado outras versões do app pode ter armazenado cache. Por isso, cada vez que você for testar novamente o sistema é ideal atualizar a página com Ctrl+F5

**Comment by guilessa** [comment]
Perfeito! Então sem problemas!
