### ISSUE TITLE
[ Outro Navegadores ] Não está brindo no Edge, Brave

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#52]
Fala time, segue o print do ocorrido.

![Captura de tela 2022-03-10 153041](https://user-images.githubusercontent.com/25805990/157731326-ed451554-19a1-4ee3-972b-2e0a9aa140b3.png)

**Comment by guilessa** [comment]
Tive esse problema também no Chrome em janela anônima.

![Captura de tela 2022-03-10 154654](https://user-images.githubusercontent.com/25805990/157734537-bfbb58ba-1142-4cd7-9645-04eeaae6fa2a.png)
![Captura de tela 2022-03-10 154942](https://user-images.githubusercontent.com/25805990/157734546-e996bb8c-7646-4281-bb61-e6dd635c7772.png)

**Comment by guilessa** [comment]
Login do painel do cliente: https://app.postbaker.com.br/1gtdZl1tWCRoL40I
Senha: 12345

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/159137722-2790b6e4-d9f2-49fd-905a-d584561667ea.png)  
Problemas de erro da classe 400 (401 e 403) estão relacionados à autenticação, é possível que por acaso vc tenha colocado a senha errado, por exemplo, o NumLock estava desativado e vc utilizou o NumPad para digitar "12345" é uma possibilidade. Essa imagem foi feita com a mesma senha.

**Comment by filiperochalopes** [comment]
![image](https://user-images.githubusercontent.com/34348097/159137778-e0482be9-d10f-4d11-ad25-4d3364f95dad.png)  
Todavia em casos de erro de senha deveria aparecer essa mensagem. De qualquer forma foi algum erro de autenticação que não está mais acontecendo. o teste foi feito em brave. Favor conferir novamente e lembrar de atualizar a página com Ctrl+F5 para garantir a limpeza de cache

**Comment by lucasnetwork** [comment]
![Captura de Tela (752)](https://user-images.githubusercontent.com/47489963/159137797-2c1f5187-21c6-4811-9a0b-29ab1f384939.png)
Testei também, e todos os meus testes foram no brave

**Comment by guilessa** [comment]
Show time, obrigado pelo help!
