### ISSUE TITLE
[ Esqueci Senha ] Altera o sub-texto

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#7]
Alterar o sub-texto onde está SOCIALPIPE para Post Baker.

**Comment by lucasnetwork** [comment]
![Captura de Tela (411)](https://user-images.githubusercontent.com/47489963/125101052-2be18d00-e0b0-11eb-9dfa-64747dde5d49.png)
Consertado

**Comment by guilessa** [comment]
Perfeito!
