### ISSUE TITLE
[ Cadastro ] Adicionar botão de POLITICA DE PRIVACIDADE ao check

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#8]
Deixa o texto como esse abaixo, TERMOS DE USO destacado com um link, esse link mesmo inclusive. 

Ao se cadastrar, declaro ter lido e aceito os [termos de uso](https://postbaker.com.br/politica-privacidade).

**Comment by lucasnetwork** [comment]
https://user-images.githubusercontent.com/47489963/125101942-26d10d80-e0b1-11eb-8ff0-145fc7663a08.mp4

Adicionado, adicionei o link do termos de uso que está no comentário.

**Comment by guilessa** [comment]
Perfeito!
