### ISSUE TITLE
[ Cadastro ] Altera sub-texto

### ISSUE THREAD

**Issue by guilessa** [Social-Pipe/social-docker#9]
Alterar SOCIAL PIPE para Post Baker. 

"Preencha o campo abaixo com o seu email cadastrado aqui na **Social Pipe** para recuperar a sua senha."

**Comment by lucasnetwork** [comment]
![Captura de Tela (412)](https://user-images.githubusercontent.com/47489963/125101619-cc37b180-e0b0-11eb-9507-eae70f6531dd.png)

Alterado o texto

**Comment by guilessa** [comment]
Perfeito!
